apiVersion: v1
kind: Service
metadata:
  name: c7-frontend
  namespace: c7-preprod
spec:
  type: LoadBalancer
  selector:
    app: c7-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80